"""empty message

Revision ID: 19804faef4fd
Revises: b9ef0d230440
Create Date: 2021-04-12 20:06:10.078517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19804faef4fd'
down_revision = 'b9ef0d230440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('count_views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'count_views')
    # ### end Alembic commands ###
