"""empty message

Revision ID: 1ae4336b42b3
Revises: 917d59367d22
Create Date: 2021-07-11 18:22:25.291814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae4336b42b3'
down_revision = '917d59367d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('roles_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    with op.batch_alter_table('user_which_viewed_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_which_viewed_post_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_which_viewed_post_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('user_which_viewed_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_which_viewed_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_which_viewed_post_id'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))
        batch_op.create_unique_constraint('roles_name_key', ['name'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_id'))

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_id'))

    # ### end Alembic commands ###
