"""empty message

Revision ID: 1d183ce42a56
Revises: 2209892c9694
Create Date: 2021-06-20 11:33:50.789365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d183ce42a56'
down_revision = '2209892c9694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.SMALLINT(),
               nullable=False)
        batch_op.drop_constraint('users_role_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('users_role_fkey', 'roles', ['role'], ['id'])
        batch_op.alter_column('role',
               existing_type=sa.SMALLINT(),
               nullable=True)

    # ### end Alembic commands ###
