"""empty message

Revision ID: 2070a1f984ac
Revises: 208c7e2b9a7f
Create Date: 2021-06-20 13:21:20.648067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2070a1f984ac'
down_revision = '208c7e2b9a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lvl_of_admin')
        batch_op.drop_column('is_banned')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_banned', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lvl_of_admin', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
