"""empty message

Revision ID: 21ee00b183d9
Revises: bd439b4d418b
Create Date: 2021-11-19 11:41:11.493783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ee00b183d9'
down_revision = 'bd439b4d418b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activeip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activeip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activeip_ip'), ['ip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activeip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activeip_ip'))

    op.drop_table('activeip')
    # ### end Alembic commands ###
