"""empty message

Revision ID: 2209892c9694
Revises: c0a8106df91d
Create Date: 2021-06-19 22:48:05.762968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2209892c9694'
down_revision = 'c0a8106df91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.SmallInteger(), nullable=True))
        batch_op.drop_constraint('users_role_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_role_id_fkey', 'roles', ['role_id'], ['id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###
