"""empty message

Revision ID: 31cbc1857fe4
Revises: 9ef0730a0a03
Create Date: 2021-07-07 11:48:32.168917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cbc1857fe4'
down_revision = '9ef0730a0a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
