"""empty message

Revision ID: 331fea1f1ad2
Revises: a682a00af5f8
Create Date: 2021-06-19 21:38:13.839099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331fea1f1ad2'
down_revision = 'a682a00af5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['users'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_role_fkey', type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_role_fkey', 'roles', ['role'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('users')

    # ### end Alembic commands ###
