"""empty message

Revision ID: 379f557c87e9
Revises: c2e2cd553e63
Create Date: 2021-07-04 21:51:49.259625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379f557c87e9'
down_revision = 'c2e2cd553e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_column('src_to_avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src_to_avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
