"""empty message

Revision ID: 5af55ef571c5
Revises: a75cb0bdb227
Create Date: 2021-03-29 23:46:19.590876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af55ef571c5'
down_revision = 'a75cb0bdb227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'author_name')
    # ### end Alembic commands ###
