"""empty message

Revision ID: 917d59367d22
Revises: 3409addb8102
Create Date: 2021-07-08 13:42:53.677751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917d59367d22'
down_revision = '3409addb8102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_to_avatar', sa.String(length=300), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('author_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('users')

    with op.batch_alter_table('user_which_viewed_post', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('real_location', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.drop_column('is_banned')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('lvl_of_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lvl_of_admin', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_banned', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('role_id')
        batch_op.drop_column('real_location')
        batch_op.drop_column('location')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    with op.batch_alter_table('user_which_viewed_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['users'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=False))

    op.drop_table('avatars')
    # ### end Alembic commands ###
