"""empty message

Revision ID: 984e9b8b1132
Revises: 06af724501e3
Create Date: 2021-06-19 20:43:12.690177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984e9b8b1132'
down_revision = '06af724501e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
