"""empty message

Revision ID: 99fded7a0944
Revises: 22f36db32072
Create Date: 2021-07-04 21:52:34.205421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fded7a0944'
down_revision = '22f36db32072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_column('filename')
        batch_op.drop_column('src_to_avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src_to_avatar', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
