"""empty message

Revision ID: a682a00af5f8
Revises: ecd294505940
Create Date: 2021-06-19 20:46:51.712746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a682a00af5f8'
down_revision = 'ecd294505940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        batch_op.drop_constraint('users_rol_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])
        batch_op.drop_column('rol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_rol_fkey', 'roles', ['rol'], ['id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###
