"""empty message

Revision ID: a8b1c504e022
Revises: 695f7cbd85c0
Create Date: 2021-04-12 19:23:27.547254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b1c504e022'
down_revision = '695f7cbd85c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_which_viewed_post', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_which_viewed_post', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
