"""empty message

Revision ID: b9ef0d230440
Revises: 625cd672baeb
Create Date: 2021-03-30 10:07:17.971281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ef0d230440'
down_revision = '625cd672baeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'author_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_name', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
