"""empty message

Revision ID: bd439b4d418b
Revises: 
Create Date: 2021-11-06 11:20:09.769682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd439b4d418b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bannedip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bannedip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bannedip_ip'), ['ip'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ban_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_banned', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('time_banned')
        batch_op.drop_column('is_banned')
        batch_op.drop_column('ban_time')

    with op.batch_alter_table('bannedip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bannedip_ip'))

    op.drop_table('bannedip')
    # ### end Alembic commands ###
