"""empty message

Revision ID: c2e2cd553e63
Revises: 7145fb77a1ad
Create Date: 2021-07-04 17:39:41.782694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e2cd553e63'
down_revision = '7145fb77a1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_to_avatar', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatars')
    # ### end Alembic commands ###
