"""empty message

Revision ID: cb8eafeed90f
Revises: 19804faef4fd
Create Date: 2021-04-12 20:07:31.692160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8eafeed90f'
down_revision = '19804faef4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'count_views',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'count_views',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
