"""empty message

Revision ID: cd27257a4ed8
Revises: d69475a28159
Create Date: 2021-04-30 13:42:44.246749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd27257a4ed8'
down_revision = 'd69475a28159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lvl_of_admin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lvl_of_admin')
    # ### end Alembic commands ###
