"""empty message

Revision ID: d273d546b6d2
Revises: 74c965ab292b
Create Date: 2021-06-18 20:33:32.573351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd273d546b6d2'
down_revision = '74c965ab292b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
