"""empty message

Revision ID: ecd294505940
Revises: 984e9b8b1132
Create Date: 2021-06-19 20:44:52.401579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd294505940'
down_revision = '984e9b8b1132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.Integer(), nullable=True))
        batch_op.drop_constraint('users_role_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['rol'], ['id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_role_fkey', 'roles', ['role'], ['id'])
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
